### ISSUE TITLE
Duplication Glitch

### ISSUE THREAD

**Issue by azulflame** [SquidDev-CC/ComputerCraft#1] opened 2017-08-09 16:08 UTC
Interaction with GriefPrevention (griefprevention-1.12-3.2.0.299.jar)
This was on the AirWavesv2 server, CC version unknown. MC 1.12

setup: The disk drive is located in a GriefPrevention claim, and the user is /containertrust ed.

Actions: When an item is in the disk drive, and the user (who is not allowed to break it) attempts to break it, the item is dropped, GriefPrevention replaces the disk drive, and places the item back in, resulting in 2 items - one dropped and one located in the disk drive. Exact NBT data is copied, including computer IDs and item enchantments.

Edit: It also happens with Turtles (normal and advanced) and with printers).

**Comment by SquidDev** [comment] 2017-08-09 21:14
I'm unable to reproduce with the following setup:

 - **GriefPrevention:** 1.12-3.2.0.303
 - **LuckPerms:** 3.2.66
 - **Sponge:** 1.12-2397-7.0.0-BETA-2462

I'll have a word with Danny to in order to confirm these are the correct options.

@azulflame, are you sure you haven't given any more permissions beyond `/containertrust`?

**Comment by azulflame** [comment] 2017-08-09 22:53
I replicated it again. The person breaking it has to have /containertrust in the plot, but cannot have build perms (/trust). And the person breaking it must not have a GriefPrevention bypass permission, like the admins on the server do

**Comment by SquidDev** [comment] 2017-10-06 09:55
I'm closing for now as I do not believe this is a ComputerCraft issue.

**Closed by SquidDev** 2017-10-06 09:55 UTC
Labels: bug
